version: 1.2
workflows:
  - subclass: WDL
    name: PharmCAT-Pipeline
    primaryDescriptorPath: /pipeline/PharmCAT_Pipeline.wdl
    readMePath: /pipeline/README.md
    filters:
      tags:
        - /v\d+.*/

  - subclass: WDL
    name: PharmCAT-VCF_Preprocessor
    primaryDescriptorPath: /modules/vcf_preprocessor.wdl
    readMePath: /modules/README.md
    filters:
      tags:
        - /v\d+.*/
