version: 1.2
workflows:
  - name: PharmCAT-Pipeline
    subclass: WDL
    primaryDescriptorPath: /dockstore/pipeline/PharmCAT_Pipeline.wdl
    testParameterFiles:
      - /pipeline/test.json
    readMePath: /pipeline/README.md
    filters:
      tags: /v.*/
