version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /pipeline/PharmCAT_Pipeline.wdl
    name: PharmCAT-Pipeline
    readMePath: /pipeline/README.md
    testParameterFiles:
      - /pipeline/test.json

  - subclass: WDL
    primaryDescriptorPath: /generic/PharmCAT.wdl
    name: PharmCAT
    readMePath: /generic/README.md
    testParameterFiles:
      - /generic/test.json
